In [ ]:
import pickle
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from docx import Document
from sklearn.model_selection import train_test_split

def docx_table_to_csv(docx_path, csv_path):
  doc = Document(docx_path)

  # Extract the first table from the document
  if not doc.tables:
    raise ValueError("No table found in document.")

  table = doc.tables[0]
  data = [[cell.text.strip() for cell in row.cells] for row in table.rows]

  # Convert to DataFrame (using row 0 as header)
  df = pd.DataFrame(data[1:], columns=data[0])

  # Save as CSV
  df.to_csv(csv_path, index=False)
  print(f"Saved successfully to {csv_path}")


# Usage
docx_table_to_csv("Streamli_taskdocx.docx", "dataset.csv")
df = pd.read_csv("dataset.csv")


print(df.head())
print(df.info())
print(df.isnull().sum())


df = df.drop_duplicates()
df

Saved successfully to dataset.csv
   Age  Gender  AnnualIncome  SpendingScore MaritalStatus  Purchased
0   25    Male         35000             60        Single          1
1   32  Female         48000             45       Married          0
2   28    Male         52000             75        Single          1
3   45  Female         65000             30       Married          0
4   35    Male         58000             85       Married          1
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            20 non-null     int64
 1   Gender         20 non-null     str
 2   AnnualIncome   20 non-null     int64
 3   SpendingScore  20 non-null     int64
 4   MaritalStatus  20 non-null     str
 5   Purchased      20 non-null     int64
dtypes: int64(4), str(2)
memory usage: 1.3 KB
None
Age              0
Gender           0
AnnualIncome     0
SpendingScore    0
MaritalStatus    0
Purchased        0
dtype: int64

    Age  Gender  AnnualIncome  SpendingScore MaritalStatus  Purchased
0    25    Male         35000             60        Single          1
1    32  Female         48000             45       Married          0
2    28    Male         52000             75        Single          1
3    45  Female         65000             30       Married          0
4    35    Male         58000             85       Married          1
5    29  Female         42000             65        Single          1
6    50    Male         72000             25       Married          0
7    40  Female         61000             55       Married          1
8    27    Male         39000             70        Single          1
9    38  Female         56000             40       Married          0
10   31    Male         47000             80        Single          1
11   46  Female         68000             35       Married          0
12   36    Male         60000             90       Married          1
13   30  Female         45000             68        Single          1
14   55    Male         80000             20       Married          0
15   42  Female         63000             50       Married          1
16   24    Male         34000             72        Single          1
17   48  Female         70000             28       Married          0
18   33    Male         54000             78        Single          1
19   41  Female         62000             48       Married          0

In [2]:
df["Gender"] = df["Gender"].astype(str).str.strip()
df["MaritalStatus"] = df["MaritalStatus"].astype(str).str.strip()
df["Gender"] = df["Gender"].map({"Male": 1, "Female": 0})
df["MaritalStatus"] = df["MaritalStatus"].map({"Married": 1, "Single": 0})
df

    Age  Gender  AnnualIncome  SpendingScore  MaritalStatus  Purchased
0    25       1         35000             60              0          1
1    32       0         48000             45              1          0
2    28       1         52000             75              0          1
3    45       0         65000             30              1          0
4    35       1         58000             85              1          1
5    29       0         42000             65              0          1
6    50       1         72000             25              1          0
7    40       0         61000             55              1          1
8    27       1         39000             70              0          1
9    38       0         56000             40              1          0
10   31       1         47000             80              0          1
11   46       0         68000             35              1          0
12   36       1         60000             90              1          1
13   30       0         45000             68              0          1
14   55       1         80000             20              1          0
15   42       0         63000             50              1          1
16   24       1         34000             72              0          1
17   48       0         70000             28              1          0
18   33       1         54000             78              0          1
19   41       0         62000             48              1          0

In [3]:
x=df.drop("Purchased",axis=1)
y=df["Purchased"]
x

    Age  Gender  AnnualIncome  SpendingScore  MaritalStatus
0    25       1         35000             60              0
1    32       0         48000             45              1
2    28       1         52000             75              0
3    45       0         65000             30              1
4    35       1         58000             85              1
5    29       0         42000             65              0
6    50       1         72000             25              1
7    40       0         61000             55              1
8    27       1         39000             70              0
9    38       0         56000             40              1
10   31       1         47000             80              0
11   46       0         68000             35              1
12   36       1         60000             90              1
13   30       0         45000             68              0
14   55       1         80000             20              1
15   42       0         63000             50              1
16   24       1         34000             72              0
17   48       0         70000             28              1
18   33       1         54000             78              0
19   41       0         62000             48              1

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [5]:
scaler=MinMaxScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_sclaled=scaler.transform(x_test)

In [6]:
x_train_scaled=pd.DataFrame(x_train_scaled,columns=x_train.columns)
x_test_sclaled=pd.DataFrame(x_test_sclaled,columns=x_test.columns)

In [7]:
models = {
"Logistic Regression": LogisticRegression(max_iter=1000),
"Naive Bayes": GaussianNB(),
"Decision Tree": DecisionTreeClassifier(random_state=42),
"Random Forest": RandomForestClassifier(random_state=42)
}
models

{'Logistic Regression': LogisticRegression(max_iter=1000),
 'Naive Bayes': GaussianNB(),
 'Decision Tree': DecisionTreeClassifier(random_state=42),
 'Random Forest': RandomForestClassifier(random_state=42)}

In [8]:
results={}
for name,model in models.items():
    print(f"\n====={name}=====")
    if name in ["Logistic Regression","Naive Bayes"]:
                model.fit(x_train_scaled,y_train)
                y_pred=model.predict(x_test_sclaled)  
    else:
        model.fit(x_train,y_train)
        y_pred=model.predict(x_test)

    acc=accuracy_score(y_test,y_pred)
    pre=precision_score(y_test,y_pred)
    rec=recall_score(y_test,y_pred)
    f1=f1_score(y_test,y_pred)
    results[name]=[acc,pre,rec,f1]
    print("Accuracy:",acc)
    print("precision",pre)
    print("recall",rec)
    print("f1score",f1)
    results_df=pd.DataFrame(results,index=["Accuracy","precision","recall","f1_score"]).T
    results_df

=====Logistic Regression=====
Accuracy: 0.75
precision 1.0
recall 0.5
f1score 0.6666666666666666

=====Naive Bayes=====
Accuracy: 0.75
precision 1.0
recall 0.5
f1score 0.6666666666666666

=====Decision Tree=====
Accuracy: 0.75
precision 1.0
recall 0.5
f1score 0.6666666666666666

=====Random Forest=====
Accuracy: 0.75
precision 1.0
recall 0.5
f1score 0.6666666666666666

In [9]:
best_model_name = results_df["recall"].idxmax()
print("Best model based on Recall:", best_model_name)
best_model = models[best_model_name]

if best_model_name in ["Logistic Regression", "Naive Bayes"]:
    best_model.fit(x_train_scaled, y_train)
else:
    best_model.fit(x_train, y_train)

# Saving the model
with open("model.pkl", "wb") as f:
    pickle.dump(best_model, f)

# Saving the scaler
if best_model_name in ["Logistic Regression", "Naive Bayes"]:
    with open("scaler.pkl", "wb") as f:
        pickle.dump(scaler, f)

Best model based on Recall: Logistic Regression